name: Deploy database
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy database
    if: github.event.sender.login == 'EndBug'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: stable
      - run: |
          git config user.name "$USER"
          git config user.email "$USER@users.noreply.github.com"
        env:
          USER: ${{ github.event.sender.login }}
      - run: git fetch origin
      - run: |
          git checkout origin/main database.json img
          git add database.json img
      - id: sha
        run: |
          echo "prev=$(git rev-parse origin/stable)" >> "$GITHUB_OUTPUT"
          echo "curr=$(git rev-parse origin/main)" >> "$GITHUB_OUTPUT"
      - run: 'git commit -m "chore: update db to match $CURR" -m "Executed via .github/workflows/deploy.yml"'
        env:
          CURR: ${{ steps.sha.outputs.curr }}
      - run: git push
