name: Deploy database
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy database
    if: github.event.sender.login == 'EndBug'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stable
      - run: |
          git config user.name "$USER"
          git config user.email "$USER@users.noreply.github.com"
        env:
          USER: ${{ github.event.sender.login }}
      - run: git fetch origin
      - run: 'git merge origin/main --allow-unrelated-histories -m "chore: update production database" -m "Executed via .github/workflows/deploy.yml"'
      - run: git push
